Frequency<-c(0.6,0.3,0.4,0.4,0.2,0.6,0.3,0.4,0.9,0.2)
bloodp<-c(103,87,32,42,59,109,78,205,135,176)
first<-c("bad","bad","bad","bad","good","good","good","good",NA,"bad")
second<-c("low","low","high", "high", "low", "low", "high", "high", "high", "high")
finaldecision<-c("low", "high","low","high","low","high","low","high","high","high")
results = cbind(Frequency,bloodp,first,second,finaldecision)
results.df = data.frame(Frequency,bloodp,first,second,finaldecision)
boxplot(Frequency, main="Frequency of hospital visits", ylab="Frequency", ylim=c(0,1))
boxplot(bloodp, main="Blood pressure measurement",ylab="blood", ylim=c(30,210))
hist(Frequency)
hist(bloodp)
